version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        UPSTREAM_VERSION: 1.2.0
        STAKER_SCRIPTS_VERSION: v0.1.2
    restart: unless-stopped
    volumes:
      - operator-data:/data/operator
    environment:
      LOG_LEVEL: info
      BUILDER_PROPOSALS: false
      EXTRA_OPTS: ""
volumes:
  operator-data: {}