version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        UPSTREAM_VERSION: v1.2.3
        STAKER_SCRIPTS_VERSION: v0.1.2
    restart: unless-stopped
    volumes:
      - operator-data:/root/.anchor
      - operator-keys:/root/keys
    environment:
      LOG_LEVEL: info
      SETUP_MODE: ""
      EXTRA_OPTS: ""
      EXISTING_PASSWORD: ""
      NEW_PASSWORD: ""
  dkg:
    build:
      context: dkg
      args:
        DKG_UPSTREAM_VERSION: v3.1.0
        STAKER_SCRIPTS_VERSION: v0.1.2
    restart: on-failure
    volumes:
      - operator-keys:/root/keys
      - dkg-data:/data/dkg
    environment:
      LOG_LEVEL: info
      OPERATOR_ID: ""
      EXTRA_OPTS: ""
volumes:
  operator-data: {}
  operator-keys: {}
  dkg-data: {}
