services:
  operator:
    build:
      args:
        NETWORK: mainnet
        P2P_PORT: 9100
        QUIC_PORT: 9101
    ports:
      - "9100:9100/tcp"
      - "9100:9100/udp"
      - "9101:9101/udp"
