services:
  operator:
    build:
      args:
        NETWORK: hoodi
        P2P_PORT: 9102
    ports:
      - "9102:9102/tcp"
      - "9102:9102/udp"
    environment:
      CORSDOMAIN: "http://anchor-hoodi.dappnode"
